### ISSUE TITLE
UtilityPV example file is incomplete

### ISSUE THREAD

**Issue by tjlca** [NREL/tyche#78]
Sam and Tj to complete the Utility PV file

Graphs are incomplete

**Comment by rjhanes** [comment]
@tjlca Do you still plan to add graphs to this analysis notebook, and if so, will you be able to complete this issue by the end of this month (December 2022)?

**Comment by tjlca** [comment]
I will be working on this now and get this done.

**Comment by tjlca** [comment]
#121

**Comment by rjhanes** [comment]
Closed in PR #121
