### ISSUE TITLE
#! symbol in jupyternotebook code for installing modules in python

### ISSUE THREAD

**Issue by tjlca** [NREL/tyche#95]
Not sure if the #! symbol will cause these modules to be automatically installed when running the script via command line. 
PVresidential simple ipynb file. Line 1

**Comment by SamBaldwinDOE** [comment]
I don't care either way; the code was listed in the Jupyter notebook and I
was just trying to understand it.  The way it was set up looked to me that
it was testing to see if the correct version was installed and was then
installing it if needed--but that was just my guess.

All the best,

sam

**Comment by rjhanes** [comment]
Per my previous comment, I don't think this is an issue, so I'll close it for now.
