### ISSUE TITLE
x axis labels in PV residential simple analysis notebook are out of alignment

### ISSUE THREAD

**Issue by tjlca** [NREL/tyche#96]

**Comment by rjhanes** [comment]
@TJTapajyoti Does this refer to the spacing/alignment of the 30-degree rotated x-axis labels on a few of the box-and-whisker plots? I can resolve that, if so.

**Comment by tjlca** [comment]
@rjhanes Yes that is the issue.. If you are too busy with other important stuff I can do this. Please do let me know.

**Comment by rjhanes** [comment]
@tjlca I can take care of this one.

**Comment by rjhanes** [comment]
Closed directly in `dev`
